import { useState, useEffect } from "react";

const API_BASE = import.meta.env.VITE_API_URL || "http://localhost:3000/api";

type Slip = {
  id: string;
  type: "Amad" | "Nikasi";
  kisan: string;
  bags: number;
  date: string;
  status: string;
};

export default function Approvals() {
  const [slips, setSlips] = useState<Slip[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchSlips();
    const interval = setInterval(fetchSlips, 5000); // Poll every 5s for demo
    return () => clearInterval(interval);
  }, []);

  const fetchSlips = async () => {
    try {
      const amadRes = await fetch(`${API_BASE}/amad_slips`);
      const amadData = await amadRes.json();
      
      const formattedSlips: Slip[] = amadData
        .filter((s: any) => s.status === 'pending_approval')
        .map((s: any) => ({
          id: s.id,
          type: "Amad",
          kisan: s.kisanName,
          bags: s.totalBags,
          date: new Date(s.createdAt).toLocaleString(),
          status: s.status,
        }));
      
      setSlips(formattedSlips);
    } catch (err) {
      console.error("Failed to fetch slips", err);
    } finally {
      setLoading(false);
    }
  };

  const handleApprove = async (id: string) => {
    // Optimistic UI update
    setSlips(slips.filter(s => s.id !== id));
    
    // Tell backend to update status to approved
    try {
      await fetch(`${API_BASE}/amad_slips/${id}`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ status: "approved" }),
      });
    } catch (e) {
      console.error("Approval failed", e);
      fetchSlips(); // Revert on failure
    }
  };

  return (
    <>
      <div className="page-header">
        <div>
          <h1 className="page-title">✅ Maker-Checker Approvals</h1>
          <p className="page-subtitle">Review and approve slips generated by Munim PCs</p>
        </div>
      </div>

      <div className="page-body">
        {loading ? (
          <div>Loading live slips from cloud...</div>
        ) : slips.length === 0 ? (
          <div className="empty-state">
            <div className="empty-state-icon">🎉</div>
            <div className="empty-state-title">All Caught Up!</div>
            <div className="empty-state-desc">There are no pending slips awaiting your approval.</div>
          </div>
        ) : (
          <div style={{ borderRadius: "var(--radius-lg)", overflow: "hidden", border: "1px solid var(--border-color)" }}>
            <table className="data-table">
              <thead>
                <tr>
                  <th>Slip ID</th>
                  <th>Type</th>
                  <th>Farmer Name</th>
                  <th>Total Bags</th>
                  <th>Entry Time</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {slips.map((slip) => (
                  <tr key={slip.id}>
                    <td style={{ fontWeight: 600, color: slip.type === 'Amad' ? "var(--accent-blue)" : "var(--accent-green)" }}>
                      {slip.id.substring(0, 8)}...
                    </td>
                    <td>{slip.type}</td>
                    <td>{slip.kisan}</td>
                    <td style={{ fontWeight: 700 }}>{slip.bags}</td>
                    <td>{slip.date}</td>
                    <td>
                      <div style={{ display: "flex", gap: 8 }}>
                        <button 
                          className="btn btn-success" 
                          style={{ padding: "6px 12px", fontSize: 12 }}
                          onClick={() => handleApprove(slip.id)}
                        >
                          Approve
                        </button>
                        <button className="btn btn-danger" style={{ padding: "6px 12px", fontSize: 12 }}>
                          Reject
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </>
  );
}
